### ISSUE TITLE
bug: container restarts with 139 SIGSEGV on arm64 (M1/M2/M3/M4) architecture

### ISSUE THREAD

**Issue by insider89** [erpc/erpc#231]
**Describe the bug**
We are running erpc lb on the k8s cluster. We see that application constantly restarted. In the logs I didn't see any error. The exit code is 139, which means Segmentation Fault (SIGSEGV).

**To Reproduce**
1. Use erpc version `0.0.43`

2. Use this erpc.yaml config:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: erpc
  name: erpc
  namespace: atk
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: atk
      app.kubernetes.io/name: erpc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "4001"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: erpc
    spec:
      containers:
        image: ghcr.io/erpc/erpc:0.0.43
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: erpc
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        - containerPort: 4001
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/erpc.yaml
          name: config
          subPath: erpc.yaml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: image-pull-secret-docker
      - name: image-pull-secret-ghcr
      - name: image-pull-secret-harbor
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: erpc
      serviceAccountName: erpc
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: erpc
        name: config
```

and configmap
```yaml
apiVersion: v1
data:
  erpc.yaml: |
    logLevel: info
    projects:
    - id: example
      upstreams:
      - endpoint: http://besu-node-rpc-1:8545
        id: besu-node-rpc-1
      - endpoint: http://besu-node-validator-1:8545
        id: besu-node-validator-1
    server:
      aliasing:
        rules:
        - matchDomain: '*'
          serveArchitecture: evm
          serveChain: "53771311147"
          serveProject: example
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: erpc
  name: erpc
  namespace: atk

```

3. Make this request:
```
kubectl apply -f deployment.yaml confimap.yaml
```

**Expected behavior**
Container is running without restart.

**Screenshots**

<img width="1351" alt="Image" src="https://github.com/user-attachments/assets/3764601a-c3e7-4922-89bb-154bdc568f94" />
<img width="1996" alt="Image" src="https://github.com/user-attachments/assets/9d129e3c-e691-43d3-a477-a3422b213cfb" />
<img width="712" alt="Image" src="https://github.com/user-attachments/assets/8a82c7b4-4764-4c4c-8710-862b85b66e44" />

**Relevant Logs:**
Attached
```
{"level":"trace","time":1744897479129,"message":"http: superfluous response.WriteHeader call from github.com/erpc/erpc/erpc.relevantCaller (http_timeout.go:166)"}
```

**Additional context**

[Explore Logs Apr 17 2025.json](https://github.com/user-attachments/files/19795582/Explore.Logs.Apr.17.2025.json)

**Comment by insider89** [comment]
Also reproduced on 0.0.42

**Comment by aramalipoor** [comment]
@insider89 will investigate your logs and try to reproduce...

How many requests and what's the avg. response size of those requests? Sometimes for higher scale production you might need to configure the memory + GC accordingly: https://docs.erpc.cloud/operation/production#memory-usage

Also in 0.0.43 there's a new panic metric that might be helpful to check: `erpc_unexpected_panic_total`

(A quick test would be to give it more memory and check if you see less restarts)

**Comment by aramalipoor** [comment]
Specifically the `superfluous response.WriteHeader call` log is fixed on main branch and will be included in next release, but don't think it's relevant to the Memory exit code you see.

**Comment by aramalipoor** [comment]
I see lots of `{"id":0,"params":["0x0",true],"method":"eth_getBlockByNumber"...` requests in the logs. Is that expected from your client-side? Basically asking for block 0 non-stop.

Anyway it shouldn't cause a memory failure, but if it does it's definitely a bug to be solved.

**Comment by goums** [comment]
We have same issue running `erpc:latest` docker image.
For context we are running it with `minikube` locally, and it keep crashing with exit code 139, even if giving it a large amount of memory.
However, on our cloud `kubernetes` setup, same image is running without any issue.

**Comment by insider89** [comment]
MacOS (arm64 M3)

**Comment by insider89** [comment]
I've disabled connection from graph-node to erpc, but still see these requests. Can erpc log its own requests to upstreams to check if they are live and request `"0x0"` block?

**Comment by aramalipoor** [comment]
By default it sends "latest" block requests to basically track the current state. Asking for block 0x0 is a bit odd especially with ID=0 (internal requests all get random IDs)... will consider this during investigation.

I'm experimenting with few things to reproduce with more details on MacOS:
```
services:
  erpc:
    image: ghcr.io/erpc/erpc:latest
    ulimits:
      core: -1
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - ./erpc.yaml:/root/erpc.yaml
      - ./cores:/cores
    environment:
      - GOTRACEBACK=crash
      - CORE_PATTERN=/cores/core.%e.%p
      - GODEBUG=gctrace=1
```

Will keep you posted on what I find...

**Comment by goums** [comment]
Thanks, I'm indeed also running on MacOS (M4)

**Comment by goums** [comment]
Actually no, still seeing the issue on `erpc:0.0.42`.
Bit different behavior though, on `erpc:0.0.43`, crash happens very soon after startup, while on `erpc:0.0.42` it seems less frequent.

**Comment by insider89** [comment]
Found the reason of block 0x0 requests - from blockscout.

**Comment by aramalipoor** [comment]
OK the culprit seems to be "sonic" library for json parsing: 
* https://github.com/bytedance/sonic/issues/257

And the reason I'm not seeing it is cuz I'm on M1:
* https://github.com/bytedance/sonic/pull/280

Will continue experimenting in #233 to see if I can eliminate Sonic and still keep memory usage low...

---

In the meantime they're suggesting to basically build for `amd64` when running on arm64 so that QEMU emulation is used: https://github.com/bytedance/sonic/issues/257#issuecomment-1222241495

**Comment by aramalipoor** [comment]
OK for now looks like best option is to only build for amd64 (the images and the binaries). The next image (0.0.45) should be amd64 only.

It would be great if you both can try with `ghcr.io/erpc/erpc:main`? If you're building yourself there's small changes you can do to the build: https://github.com/erpc/erpc/blob/main/Dockerfile#L30
